import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './App'
import { TooltipLayer } from './components/TooltipLayer'
import './styles.css'
import './styles/splash.css'
import './styles/language.css'
import './styles/tooltip.css'
import './styles/auth-landing.css'
import './styles/extension-authorization.css'
import './styles/admin-workspace.css'
import './styles/statistics.css'
import './styles/mail-storage-statistics.css'
import './styles/failed-mail-center.css'
import './styles/audit-logs.css'
import './styles/admin-mail-management.css'
import './styles/mailbox.css'
import './styles/mailbox-header.css'
import './styles/message-list-motion.css'
import './styles/bulk-actions.css'
import './styles/mailbox-switcher.css'
import './styles/managed-mailbox-actions.css'
import './styles/mailbox-switcher-feedback.css'
import './styles/mailbox-address-option.css'
import './styles/quick-mailbox.css'
import './styles/message.css'
import './styles/reply-attachments.css'
import './styles/email-frame-transition.css'
import './styles/message-scrollbar.css'
import './styles/message-scroll-top.css'
import './styles/message-translation.css'
import './styles/message-retry.css'
import './styles/external-link-dialog.css'
import './styles/attachment-preview.css'
import './styles/mail-delete-dialog.css'
import './styles/compose-dialog.css'
import './styles/draft-inline-editor.css'
import './styles/draft-list.css'
import './styles/responsive.css'
import './styles/user-policy-panel.css'
import './styles/user-management.css'
import './styles/account-settings.css'
import './styles/domain-management.css'
import './styles/temporary-invites.css'
import './styles/invitation-history.css'
import './styles/temporary-invite-page.css'
import './styles/system-settings.css'
import './styles/storage-policy.css'
import './styles/outbound-rate-limit.css'
import './styles/deployment-wizard.css'
import './styles/icloud-workspace.css'
import './styles/icloud-region-select.css'
import './styles/icloud-scope-switcher.css'
import './styles/linux-do-mail.css'
import './styles/gmail-dialog.css'
import './styles/gmail-workspace.css'
import './styles/api-guide.css'
import './styles/api-reference.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
    <TooltipLayer />
  </StrictMode>,
)
